startz/first/urls.py
from django.urls import path

from . import views
app_name = "first"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/",views.ChooseView.as_view(), name="choose"),
    path("<int:question_id>/vote/",views.vote, name="vote"),
    path("<int:pk>/results/",views.ResultsView.as_view(), name="results"),
]

startz/startz/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('first/',include("first.urls")),
    path('admin/', admin.site.urls),
]

startz/first/models.py
from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200,default="what's this")
    pub_date = models.DateTimeField("date published",default=timezone.now())


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE,null=True)
    choice_text = models.CharField(max_length=200,default="hello")
    votes = models.IntegerField(default=0,null=True)

startz/kitven/models.py
from django.db import models

# Create your models here.

startz/first/views.py
from django.db.models import F
from django.urls import reverse
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from .models import Question,Choice
from django.views import generic
# Create your views here.

class IndexView(generic.ListView):
    template_name = "first/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        return Question.objects.order_by("-pub_date")[:5]

class ChooseView(generic.DetailView):
    model = Question
    template_name = "first/detail.html"

class ResultsView(generic.DetailView):
    model = Question
    template_name = "first/results.html"

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "first/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("first:results", args=(question.id,)))

startz/kitven/views.py
from django.shortcuts import render

# Create your views here.

startz/first/templates/first/detail.html
<form action="{% url 'first:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form>

startz/first/templates/first/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/first/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

startz/first/templates/first/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'first:choose' question.id %}">Vote again?</a>